#include<iostream>
using namespace std;
main(){
cout << "Number 1: ";
float one;
cin >> one;
cout << "Number 2: ";
float two;
cin >> two;
cout << "Number 3: ";
float three;
cin >> three;
cout << "Number 4: ";
float four;
cin >> four;
cout << "Number 5: ";
float five;
cin >> five;
cout << "Number 6: ";
float six;
cin >> six;
cout << "Number 7: ";
float seven;
cin >> seven;
cout << "Number 8: ";
float eight;
cin >> eight;
cout << "Number 9: ";
float nine;
cin >>nine;
cout << "Number 10: ";
float ten;
cin >> ten;
cout << "Number 11: ";
float eleven;
cin >> eleven;
cout << "Number 12: ";
float twelve;
cin >> twelve;
cout << "Number 13: ";
float thirteen;
cin >> thirteen;
cout << "Number 14: ";
float fourteen;
cin >> fourteen;
cout << "Number 15: ";
float fifteen;
cin >> fifteen;
float output;
output=one+two+three+four+five;
float output1;
output1=six*seven*eight*nine*ten;
float output2;
output2=eleven-twelve-thirteen-fourteen-fifteen;
float output3;
output3=output+output1;
float output4;
output4=output3-output2;
cout<<"The final result is:"<<output4;
}

